var prgList = [
 '1|3||Basis-Adresse (kurze Adresse)',
 '2|||Minimale Geschwindigkeit',
 '3|||Faktor Beschleunigung (Anfahr-Verzögerung)',
 '4|||Faktor Bremsen (Brems-Verzögerung)',
 '5|0||Maximale Geschwindigkeit',
 '6|1||Mittlere Geschwindigkeit',
 '7|||Decoder Versionsnummer',
 '8|||Herstellerkennung',
 '9|0||PWM-Periode',
 '10|||RailCom',
 '17|192||Erweiterte Adresse (lange Adresse), High Byte',
 '18|0||Erweiterte Adresse (lange Adresse), Low Byte',
 '28|||Konfiguration RailCom',
 '29|10||Decoder-Konfiguration',
 '30|||Fehlerinformation',
 '33|1||Funktionsmapping F0 vorwärts',
 '34|2||Funktionsmapping F0 rückwärts',
 '35|4||Funktionsmapping F1 vorwärts',
 '47|0||Funktionsmapping F1 rückwärts',
 '57|0||ZIMO: max. Motorspannung in 1/10 V',
 '60|0||ZIMO: Funktionsausgänge dimmen',
 '63|51||ZIMO: Modifizieren Lichteffekte',
 '114|0||ZIMO: Dimm-Maske 1',
 '124|0||ZIMO: Rangiertaste',
 '125|0||ZIMO: Lichteffekte F0 vorne',
];
