var prgList = [
 '1|111||Basis-Adresse (kurze Adresse)',
 '2|2||Minimale Geschwindigkeit',
 '3|7||Faktor Beschleunigung (Anfahr-Verzögerung)',
 '4|5||Faktor Bremsen (Brems-Verzögerung)',
 '5|1||Maximale Geschwindigkeit',
 '6|1||Mittlere Geschwindigkeit',
 '7|14||Decoder Versionsnummer',
 '8|145||Hersteller-ID',
 '9|0||Periode Pulsweite',
 '10|0||RailCom',
 '17|0||Erweiterte Adresse (lange Adresse), High Byte',
 '18|0||Erweiterte Adresse (lange Adresse), Low Byte',
 '28|0||Konfiguration RailCom',
 '29|22||Decoder-Konfiguration',
 '30|0||Fehlerinformation',
 '33|1||Funktionsmapping F0 vorwärts',
 '34|2||Funktionsmapping F0 rückwärts',
 '35|4||Funktionsmapping F1 vorwärts',
 '47|16||Funktionsmapping F1 rückwärts',
 '57|120||ZIMO: max. Motorspannung in 1/10 V',
 '60|0||ZIMO: Funktionsausgänge dimmen',
 '63|51||ZIMO: Modifizieren Lichteffekte',
 '114|0||ZIMO: Dimm-Maske 1',
 '124|0||ZIMO: Rangiertaste',
 '125|0||ZIMO: Lichteffekte F0 vorne',
];
